export const USERS_REDUCER_ACTION_TYPES = {
    LOGIN_CURRENT_USER: "LOGIN_CURRENT_USER",
    SET_USER_SUCCEED: "SET_USER_SUCCEED",
    WATCH_FOR_FIREBASE_AUTH: 'WATCH_FOR_FIREBASE_AUTH',
    REGISTER_NEW_USER: "REGISTER_NEW_USER",
    LOGOUT_USER: 'LOGOUT_USER',
    IS_AUTH_STATE: "CHANGE: IS_AUTH_STATE",
    LOADING_STATE: "CHANGE: LOADING_STATE",
};

export const SEARCH_EVENTS_ACTION_TYPES = {
    GET_SEARCH_EVENTS: 'GET_SEARCH_EVENTS',
    GET_EVENTS_SUCCEED: 'GET_EVENTS_SUCCEED',
    LOADING_STATE: 'LOADING_STATE'
};


