export const CERTAIN_USER_REDUCER_ACTION_TYPES = {
    POST_CERTAIN_USER: "CERTAIN_USER: POST_CERTAIN_USER",
    POST_CERTAIN_USER_SUCCEED: "CERTAIN_USER: POST_CERTAIN_USER_SUCCEED"
};

export const USERS_REDUCER_ACTION_TYPES = {
    GET_USERS: "USERS: GET_USERS",
    GET_USERS_SUCCEED: "USERS: GET_USERS_SUCCEED",
    LOADING_STATE: "CHANGE: LOADING_STATE"
};

export const GET_SEARCH_EVENTS = 'GET_SEARCH_EVENTS';

export const LOADING_STATE = 'LOADING_STATE';

export const GET_ERRORS = 'GET_ERRORS';

export const SET_MAP_LOCATIONS = 'SET_MAP_LOCATIONS';
