export const USERS_REDUCER_ACTION_TYPES = {
    LOGIN_CURRENT_USER: "LOGIN_CURRENT_USER",
    LOGIN_USER_SUCCEED: "LOGIN_USER_SUCCEED",
    REGISTER_NEW_USER: "REGISTER_NEW_USER",
    IS_AUTH_STATE: "CHANGE: IS_AUTH_STATE",
    LOADING_STATE: "CHANGE: LOADING_STATE",
};

export const SEARCH_EVENTS_ACTION_TYPES = {
    GET_SEARCH_EVENTS: 'GET_SEARCH_EVENTS',
    GET_EVENTS_SUCCEED: 'GET_EVENTS_SUCCEED',
    LOADING_STATE: 'LOADING_STATE'
};


